// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/android-screens/AiChat.tsx": () => import("../components/mockups/android-screens/AiChat.tsx"),
  "./components/mockups/android-screens/Browse.tsx": () => import("../components/mockups/android-screens/Browse.tsx"),
  "./components/mockups/android-screens/Downloads.tsx": () => import("../components/mockups/android-screens/Downloads.tsx"),
  "./components/mockups/android-screens/Home.tsx": () => import("../components/mockups/android-screens/Home.tsx"),
  "./components/mockups/android-screens/PdfViewer.tsx": () => import("../components/mockups/android-screens/PdfViewer.tsx"),
  "./components/mockups/android-screens/Search.tsx": () => import("../components/mockups/android-screens/Search.tsx"),
  "./components/mockups/android-screens/Splash.tsx": () => import("../components/mockups/android-screens/Splash.tsx")
};
